---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: mer-hacker
spec:
  selector:
    app: mer-hacker
    tier: frontend
  ports:
    - protocol: "TCP"
      port: 80
      targetPort: 80
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-nginx-cg
  namespace: mer-hacker
data:
  mer-hacker.conf: |
    server {
      listen 80;
      server_name mer-hacker.nts.at;
      root /usr/share/nginx/mer-hacker/build;
      index index.html index.htm;
    
      location / {
        try_files $uri /index.html;
        error_page  405     =200 $uri;
      }

      location /flask {
            proxy_redirect                      off;
            proxy_set_header Host               $host;
            proxy_set_header X-Real-IP          $remote_addr;
            proxy_set_header X-Forwarded-For    $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto  $scheme;
            proxy_read_timeout          3m;
            proxy_connect_timeout       3m;
            proxy_pass http://flask:5000;
      }
      
      location /node {
            proxy_redirect                      off;
            proxy_set_header Host               $host;
            proxy_set_header X-Real-IP          $remote_addr;
            proxy_set_header X-Forwarded-For    $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto  $scheme;
            proxy_read_timeout          3m;
            proxy_connect_timeout       3m;
            proxy_pass http://node:3001;
      }
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mer-hacker-frontend
  namespace: mer-hacker
spec:
  minReadySeconds: 10
  replicas: 3
  selector:
    matchLabels:
      app: mer-hacker
      tier: frontend
      track: stable
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 2
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: mer-hacker
        tier: frontend
        track: stable
    spec:
      containers:
        - name: mer-hacker-frontend
          image: kyos0109/nginx-distroless:1.18.0
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          resources:
            limits:
              cpu: 200m
              memory: 400Mi
            requests:
              cpu: 200m
              memory: 400Mi
          readinessProbe:
            httpGet:
              path: /
              port: 80
              scheme: HTTP
              httpHeaders:
              - name: Host
                value: mer-hacker.nts.at
            initialDelaySeconds: 10
            timeoutSeconds: 1
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: 80
              scheme: HTTP
              httpHeaders:
              - name: Host
                value: mer-hacker.nts.at
            initialDelaySeconds: 15
            timeoutSeconds: 20
          volumeMounts:
            - name: nginx-config
              mountPath: /etc/nginx/sites-enabled/
            - name: mer-hacker-app
              mountPath: /usr/share/nginx
      volumes:
        - name: mer-hacker-app
          emptyDir: {}
        - name: nginx-config
          configMap:
            name: frontend-nginx-cg
            items:
              - key: mer-hacker.conf
                path: keys
