---
apiVersion: v1
kind: Service
metadata:
  name: rqb
  namespace: jerry
spec:
  selector:
    app: jerry
    tier: backend
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jerry-backend
  namespace: jerry
spec:
  minReadySeconds: 10
  replicas: 3
  selector:
    matchLabels:
      app: jerry
      tier: backend
      track: stable
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: jerry
        tier: backend
        track: stable
    spec:
      imagePullSecrets:
        - name: nts-artifacts-soc
      containers:
        - name: rqb
          image: docker.soc.artifacts.nts.at/rqb:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
          env:
            - name: DB_HOST
              value: "172.21.40.168"
            - name: DB_NAME
              value: "postgres"
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: jerry-db-secret
                  key: DB_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: jerry-db-secret
                  key: DB_PASSWORD
            - name: GITLAB_URL
              value: "https://gitlab.nts.at/"
            - name: GITLAB_PROJECT
              value: "socinternal/configparser/readiness-check-sql-queries"
            - name: GITLAB_TOKEN
              valueFrom:
                secretKeyRef:
                  name: jerry-gitlab-secret
                  key: GITLAB_TOKEN
          volumeMounts:
            - name: jerry-nfs
              mountPath: "/jerry/templates"
      volumes:
        - name: jerry-nfs
          persistentVolumeClaim:
            claimName: jerry-nfs-pvc
