---
apiVersion: v1
kind: Service
metadata:
  name: flask
  namespace: mer-hacker
spec:
  selector:
    app: mer-hacker
    tier: backend
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mer-hacker-backend
  namespace: mer-hacker
spec:
  minReadySeconds: 10
  replicas: 3
  selector:
    matchLabels:
      app: mer-hacker
      tier: backend
      track: stable
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: mer-hacker
        tier: backend
        track: stable
    spec:
      containers:
        - name: mer-hacker-backend-flask
          image: python:3.7-slim
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
