# Stage 0, "build-stage", based on Node.js, to build and compile the frontend
FROM node:latest as build-stage

ADD ./package.json /mer-hacker/
ADD ./config-overrides.js /mer-hacker/
ADD ./README.md /mer-hacker/
ADD ./public /mer-hacker/public
ADD ./src /mer-hacker/src
ADD ./node /mer-hacker/node

WORKDIR /mer-hacker

RUN npm install && \
    npm run build-rewired

# Stage 1, based on Nginx, to have only the compiled app, ready for production with Nginx
#FROM kyos0109/nginx-distroless:1.18.0
FROM busybox:latest

COPY --from=build-stage /mer-hacker/build/ /deploy/mer-hacker/build
