version: '3'
services:
  flask:
    image: mer-hacker-flask:latest
    hostname: flask

    expose:
      - 5000
    restart: on-failure
    stop_grace_period: 120s

  mer-hacker:
    image: mer-hacker:latest
    hostname: mer-hacker
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - type: volume
        source: nginxconfig
        target: /etc/nginx/sites-enabled
    stop_grace_period: 30s
    restart: on-failure
    depends_on:
      - flask


volumes:
  nginxconfig:

