# Stage 0, "build-stage", based on Node.js, to build and compile the frontend
FROM cyberfrollo/jerry-node:latest as build-stage

# FROM cyberfrollo/jerry-node as build-stage

WORKDIR /jerry

COPY package*.json /jerry/
COPY rqb/ /jerry/rqb/
ADD templates/ /jerry/templates/

RUN npm install

RUN npm run build


# Stage 1, based on Nginx, to have only the compiled app, ready for production with Nginx
FROM cyberfrollo/jerry:latest

COPY --from=build-stage /jerry/build/ /usr/share/nginx/jerry/build
COPY --from=build-stage /jerry/rqb/ /usr/share/nginx/jerry/rqb
COPY --from=build-stage /jerry/templates/ /usr/share/nginx/jerry/templates

RUN pip3 install -r /usr/share/nginx/jerry/rqb/requirements.txt

RUN pip uninstall --yes python-gitlab
RUN pip install python-gitlab

# Copy the default nginx.conf provided by cyberfrollo/jerry-node

COPY --from=build-stage /nginx.conf /etc/nginx/conf.d/default.conf