---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: jerry-nfs-pv
spec:
  capacity:
    storage: 3Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs
  mountOptions:
    - hard
    - nfsvers=4.0
  nfs:
    path: /jerry
    server: 172.21.40.166
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jerry-nfs-pvc
  namespace: jerry
spec:
  storageClassName: nfs
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 3Gi
