
# Stage 0, "build-stage", based on Node.js, to build and compile the frontend
FROM node:latest as build-stage

ADD ./package.json /mer-hacker/
ADD ./public /mer-hacker/public
ADD ./src /mer-hacker/src

WORKDIR /mer-hacker

RUN npm install && \
    npm run build


# Stage 1, based on Nginx, to have only the compiled app, ready for production with Nginx
FROM nginx:1.16.0-alpine


# COPY build /usr/share/nginx/mer-hacker/build

COPY --from=build-stage /mer-hacker/build/ /usr/share/nginx/mer-hacker/build


# Copy the default nginx default.conf provided by DockersMer-hacker/ngnix/default.conf

COPY DockersMer-hacker/ngnix/default.conf /etc/nginx/conf.d/default.conf