





###
###
GET http://localhost:3001/node/flask/logs/log_file.log

###
###
GET http://localhost:3001/node/flask/backup_restore/meraki_restore_network.py

###



###
POST http://localhost:3001/node/clear-cookie
Content-Type: application/json 
Accept : */*

{
    
     "sessionID": "7H_F5XhfzFEgp0bn8n6zP8SUbw_jAF77"
    
}

###
POST http://localhost:3001/node/read-cookie
Content-Type: application/json 
Accept : */*

{
    
    "username": "admin"
    
}

###

POST http://localhost:3001/node/set-cookie
Content-Type: application/json 
Accept : */*

{
    
    "user": "admin"
    
}

###

POST http://localhost:3001/node/hash-users
Content-Type: application/json 
Accept : */*

{
    "username": "test", "password": "1234", "apiKey":"tzu",
    "signed": "false"

}

###

POST http://localhost:3001/node/authenticate
Content-Type: application/json

{
    "username": "admin", "password": "s0sosd"

}


###

POST http://localhost:3001/node/write_templateFile
Content-Type: application/json

{
    "test": "ciao"

}







###
GET http://localhost:3001/node/dump






###
GET http://localhost:3001/node/get-api-key





###
POST http://localhost:3001/node/get-api-key
Content-Type: application/json

{
    "username": "ENCRYPT"

}



###
POST http://localhost:3001/node/post-api-key
Content-Type: application/json

{
    "username": "ENCRYPT",
    "apiKey": "zulu"

}

###
POST http://localhost:3001/node/delete_debugfile





###
GET http://localhost:5000/flask/change_log



###
POST http://localhost:3001/node/get-AlreadyisSignedIn
Content-Type: application/json


{
    "username": "admin"
}


###
POST http://localhost:3001/node/post-AlreadyisSignedIn
Content-Type: application/json

{
    "username": "admin",
    "signed": false

}


###
POST http://localhost:3001/node/upload_backupfile
Content-Type: text/plain


"ciao"




###
GET http://165.22.30.93/flask/organizations
