

###
GET http://localhost:3001/clear-cookie

###
GET http://localhost:3001/read-cookie

###



GET http://localhost:3001/set-cookie

###

POST http://localhost:3001/hash-users
Content-Type: application/json 
Accept : */*

{
    "username": "admin", "password": "8dudjd"

}

###

POST http://localhost:3001/authenticate
Content-Type: application/json

{
    "username": "admin", "password": "s0sosd"

}







###
GET http://localhost:3001/dump






###
GET http://localhost:3001/get-api-key


###
POST http://localhost:3001/post-api-key
Content-Type: application/json

{
    "key": "778zeuhsh"

}

###
POST http://localhost:3001/delete_debugfile